#!/bin/bash
# GitHub Push Script
# Replace YOUR_USERNAME with your actual GitHub username before running

echo "🚀 Pushing AI Quiz Management System to GitHub..."
echo ""
echo "📋 Steps to complete the push:"
echo ""
echo "1. Create a new repository on GitHub.com:"
echo "   - Repository name: ai-quiz-management-system"
echo "   - Description: AI-powered Quiz Management System with Google Gemini integration"
echo "   - Make it Public or Private as you prefer"
echo "   - Do NOT initialize with README (we already have one)"
echo ""
echo "2. Replace YOUR_USERNAME below with your GitHub username and run these commands:"
echo ""
echo "   git remote set-url origin https://github.com/YOUR_USERNAME/ai-quiz-management-system.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. When prompted for credentials:"
echo "   - Username: Your GitHub username"
echo "   - Password: Your Personal Access Token (not your GitHub password)"
echo ""
echo "🔗 Get a Personal Access Token at:"
echo "   https://github.com/settings/tokens/new"
echo "   - Select 'repo' scope"
echo "   - Copy the token and use it as your password"
echo ""
echo "✅ Your repository is ready to push!"
echo "   Total files: 40"
echo "   Total lines of code: 6,803+"
echo ""
echo "🎉 After pushing, your project will be available at:"
echo "   https://github.com/YOUR_USERNAME/ai-quiz-management-system"
