"""Add shuffled_question_ids column to quiz_session table

Revision ID: 6575ff16d686
Revises: 44ead1abece0
Create Date: 2025-08-11 10:25:33.410513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6575ff16d686'
down_revision = '44ead1abece0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffled_question_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.drop_column('shuffled_question_ids')

    # ### end Alembic commands ###
